# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 120, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 15px;\n"
"    border:1px solid #fff;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 240, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 15px;\n"
"    border:1px solid #fff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(790, 440, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 15px;\n"
"    border:1px solid #fff;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 120, 751, 431))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 500, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#028AFD")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setStyleSheet("color:#00D57B")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 510, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#028AFD")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(790, 500, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 15px;\n"
"    border:1px solid #fff;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.fb_2 = QtWidgets.QPushButton(self.centralwidget)
        self.fb_2.setGeometry(QtCore.QRect(50, 580, 931, 31))
        font = QtGui.QFont()
        font.setFamily("FF Shamel Family")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.fb_2.setFont(font)
        self.fb_2.setStyleSheet("border-radius: 3px;")
        self.fb_2.setText("")
        self.fb_2.setObjectName("fb_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 550, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 5px;\n"
"    border:1px solid #fff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 20, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setStyleSheet("color:#028AFD")
        self.label_5.setObjectName("label_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(790, 180, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #028AFD;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00D170;\n"
"    border-radius: 15px;\n"
"    border:1px solid #fff;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.time = QtWidgets.QLineEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(830, 580, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setToolTip("")
        self.time.setToolTipDuration(-1)
        self.time.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.time.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(238, 238, 236);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #dedede;\n"
"    color: #046EC7;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(186, 189, 182);\n"
"}")
        self.time.setObjectName("time")
        self.news = QtWidgets.QLineEdit(self.centralwidget)
        self.news.setGeometry(QtCore.QRect(30, 580, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Omnes Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.news.setFont(font)
        self.news.setToolTip("")
        self.news.setToolTipDuration(-1)
        self.news.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.news.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(238, 238, 236);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #dedede;\n"
"    color: #046EC7;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(186, 189, 182);\n"
"}")
        self.news.setText("")
        self.news.setObjectName("news")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "تعريف الاصناف"))
        self.pushButton_3.setText(_translate("MainWindow", "فاتـــــــورة بيــــــع"))
        self.pushButton_4.setText(_translate("MainWindow", "دفتـر الـديـــون"))
        self.label.setText(_translate("MainWindow", "img"))
        self.label_2.setText(_translate("MainWindow", "El SAYAFF"))
        self.label_3.setText(_translate("MainWindow", "اختر بنفسكِ من أنتِ وماذا تريد، من خلال أسلوبكِ في الملابس وطريقة عيشكِ."))
        self.label_4.setText(_translate("MainWindow", "S H O P"))
        self.pushButton_5.setText(_translate("MainWindow", "بــــحــــث ســريع"))
        self.pushButton_2.setText(_translate("MainWindow", "برمجة: محمد جمال رضوان"))
        self.label_5.setText(_translate("MainWindow", "برنامج (حساباتي)"))
        self.pushButton_6.setText(_translate("MainWindow", "فاتـــــــورة شراء"))
        self.time.setText(_translate("MainWindow", "الساعة الان: "))
